// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqltaqvfSypUBunTKIEFw6wzTqmz-Hm68',
    appId: '1:1038258745288:web:f6d0b5674ca6ed20dcdafd',
    messagingSenderId: '1038258745288',
    projectId: 'jommasjid-app',
    authDomain: 'jommasjid-app.firebaseapp.com',
    storageBucket: 'jommasjid-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9_bI6mzYC9IF7swSznEdimWeiqVZwWbI',
    appId: '1:1038258745288:android:aaa6fd28e0f53fb5dcdafd',
    messagingSenderId: '1038258745288',
    projectId: 'jommasjid-app',
    storageBucket: 'jommasjid-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByRZ39Mt4_SYTFAYqHtAcsQfuaabV5H3g',
    appId: '1:1038258745288:ios:9738bd331543da16dcdafd',
    messagingSenderId: '1038258745288',
    projectId: 'jommasjid-app',
    storageBucket: 'jommasjid-app.firebasestorage.app',
    iosBundleId: 'com.example.jomMasjid',
  );
}
